include theos/makefiles/common.mk

BUNDLE_NAME = PortraitLock
PortraitLock_FILES = Switch.x
PortraitLock_FRAMEWORKS = UIKit
PortraitLock_LIBRARIES = flipswitch
PortraitLock_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk
